[project]
name = "bagl"
version = "0.1.0"
description = "Simple LLM agent Python library powered by BAML"
readme = "README.md"
authors = [
    { name = "Daniel Barker", email = "dcbark01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
