[project]
name = "bagl"
version = "0.1.0"
description = "Simple LLM agent Python library powered by BAML"
readme = "README.md"
authors = [
    { name = "Daniel Barker", email = "dcbark01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pyclean>=3.1.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.7",
    "rust-just>=1.42.4",
    "ty>=0.0.1a20",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py312"
line-length = 120
lint.select = [
    "F",      # pyflakes
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "I",      # isort
]
lint.ignore = [
    "PTH123", # use Path.open instead of open
]
exclude = [
    "baml_src/*",
    "baml_client/*",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.isort]
known-first-party = ["bagl"]
length-sort = true
length-sort-straight = true
lines-after-imports = 2
no-lines-before = ["standard-library", "local-folder"]

# [tool.pytest.ini_options]

[tool.coverage.run]
omit = [
    # "*/__init__.py",
    # exclude code auto-generated by baml from coverage
    "baml_client/*",
]
